name: Network Upgrade Tests - Overall contracts
on:
  workflow_dispatch

jobs:
  contract-state:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      
      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: EVM test
        run: |
          npm install -g yarn
          yarn install
          yarn run build
          yarn run test-ctx-overall
        env:
          EVM_CTX_DEPLOYER_KEY: ${{ secrets.EVM_CTX_DEPLOYER_KEY }}
        working-directory:
          ts-tests/evm

      - name: Ink test
        run: |
          npm i --force
          npm run test-ctx-overall
        env:
          INK_CTX_DEPLOYER_URI: ${{ secrets.INK_CTX_DEPLOYER_URI }}
        working-directory:
          ts-tests/ink